#!/bin/bash

set -u

#
# Robert Brockway
# 16 Sept 2022
#

#
# Config
#

BASEURL="https://storage.googleapis.com"
KUBEURL="$BASEURL/kubernetes/release/release"

#
# Functions
#

cleanup()
{
	echo "Removing working directory"
	rm -rf $WORKDIR
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 90
		;;
	esac

}

downloadKubectl()
{
	echo "Getting kubectl version"
	VERSION=$(curl -s "$KUBEURL/stable.txt")
	case $? in
	0)
		echo "Version: $VERSION"
		;;
	*)
		error 50
		;;
	esac

	echo "Downloading kubectl"
	curl -sLO "$KUBEURL/$VERSION/bin/linux/amd64/kubectl"
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 55
		;;
	esac
}

installKubectl()
{
	echo "Making kubectl available"
	cp kubectl /usr/local/bin
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 64
		;;
	esac

	echo "Setting permissions on kubectl"
	chmod a+x /usr/local/bin/kubectl
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 65
		;;
	esac
}

error()
{
	case $1 in
	20)
		MESSAGE="Command $2 not available"
		;;
	25)
		MESSAGE="Unable to create working directory"
		;;
	28)
		MESSAGE="Unable to change directory to working directory"
		;;
	50)
		MESSAGE="Attempt to download kubectl failed"
		;;
	60)
		MESSAGE="Attempt to install kubectl failed"
		;;
	65)
		MESSAGE="Attempt to set permissions on kubectl failed"
		;;
	90)
		MESSAGE="Unable to remove working directory"
		;;
	*)
		MESSAGE="Unknown error"
		;;
	esac

	echo $MESSAGE
	logger $MESSAGE
}

initialise()
{
	# We need these commands for the script to complete
	COMMANDLIST="curl logger mktemp unzip"

	for I in $COMMANDLIST
	do
		command -v $I &> /dev/null
		case $? in
		0)
			echo "Command $I available"
			;;
		*)
			error 20 $I
			;;
		esac
	done

	WORKDIR=$(mktemp -d /tmp/kubectl-install-XXXXXX)
	case $? in
	0)
		echo "Working directory $WORKDIR created successfully"
		;;
	*)
		error 25
		;;
	esac

	cd $WORKDIR
	case $? in
	0)
		echo "Changed directory to working directory"
		;;
	*)
		error 28
		;;
	esac
}


#
# Main
#

initialise
downloadKubectl
installKubectl
cleanup
