#!/bin/bash

set -u

#
# Robert Brockway
# 16 Sept 2022
#

#
# Config
#

#BASEURL="https://storage.googleapis.com"
BASEURL="https://dl.k8s.io"
#KUBEURL="$BASEURL/kubernetes/release/release"
#KUBEURL="$BASEURL/release"
KUBEURL="$BASEURL"

#
# Functions
#

cleanup()
{
	echo "Removing working directory"
	rm -rf $WORKDIR
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 90
		;;
	esac

}

downloadKubectl()
{
	echo "Getting kubectl version"
	VERSION=$(curl -s "$KUBEURL/stable.txt")
	case $? in
	0)
		echo "Version: $VERSION"
		;;
	*)
		error 50
		;;
	esac

	echo "Downloading kubectl"
	#curl -sLO "$KUBEURL/$VERSION/bin/linux/amd64/kubectl"
	curl -sLO "https://dl.k8s.io/v1.25.2/bin/linux/amd64/kubectl"
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 55
		;;
	esac
}

downloadMinikube()
{
	wget $BASEURL/minikube/releases/latest/minikbbe-linux-amd64
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 60
		;;
	esac


}

installKubectl()
{
	echo "Making kubectl available"
	cp kubectl /usr/local/bin
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 64
		;;
	esac

	echo "Setting permissions on kubectl"
	chmod a+x /usr/local/bin/kubectl
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 65
		;;
	esac
}

installMiniKube()
{
	cp minikube-linux-amd64 /usr/local/bin/minikube
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 70
		;;
	esac

	chmod 755 /usr/local/bin/minikube
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 73
		;;
	esac

	minikube version
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 76
		;;
	esac
}


error()
{
    echo "Error: $1"
    logger "Error: $1"
    exit $1
}

initialise()
{
	# We need these commands for the script to complete
	COMMANDLIST="curl logger mktemp unzip"

	for I in $COMMANDLIST
	do
		command -v $I &> /dev/null
		case $? in
		0)
			echo "Command $I available"
			;;
		*)
			error 20
			;;
		esac
	done

	WORKDIR=$(mktemp -d /tmp/kubectl-install-XXXXXX)
	case $? in
	0)
		echo "Working directory $WORKDIR created successfully"
		;;
	*)
		error 25
		;;
	esac

	cd $WORKDIR
	case $? in
	0)
		echo "Changed directory to working directory"
		;;
	*)
		error 28
		;;
	esac
}

startMinikube()
{
	minikube start
	case $? in
	0)
		echo "Success!"
		;;
	*)
		error 80
		;;
	esac
}

#
# Main
#

initialise
downloadKubectl
installKubectl
downloadMinikube
installMiniKube
startMinikube
cleanup
