#!/bin/bash

#
# Functions
#

downloadScript
{
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
	case $? in
	0)
		true
		;;
	*)
		error 50
		;;
	esac
}

error()
{
    echo "Error: $1"
    logger "Error: $1"
    exit $1
}

installNVM()
{
	nvm install --lts
	case $? in
	0)
		true
		;;
	*)
		error 90
		;;
	esac

}

loadNVM()
{
	if [ -d "$HOME/.nvm" ]; then
		export NVM_DIR="$HOME/.nvm"
		case $? in
		0)
			true
			;;
		*)
			error 60
			;;
		esac


		# This loads nvm
		[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
		case $? in
		0)
			true
			;;
		*)
			error 63
			;;
		esac

		# This loads nvm bash_completion
		[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
		case $? in
		0)
			true
			;;
		*)
			error 66
			;;
		esac

	fi
}

reinitialiseBASH()
{
	source ~/.bashrc
	case $? in
	0)
		true
		;;
	*)
		error 70
		;;
	esac

}

verifyNVM()
{
	command -v nvm
	case $? in
	0)
		true
		;;
	*)
		error 80
		;;
	esac

}

#
# Main
#

downloadScript
loadNVM
reinitialiseBASH
verifyNVM
installNVM
