#############
# Repo Keys #
#############

- name: install apt-transport-https
  apt: name=apt-transport-https state=present

#- name: Adding Microsoft Repo Key
#  apt_key:
#    url: https://packages.microsoft.com/keys/microsoft.asc

#- name: Adding VirtualBox Repo Key
#  apt_key:
#    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

#- name: Adding Vivaldi Repo Key
#  apt_key:
#    url: http://repo.vivaldi.com/stable/linux_signing_key.pub


#########
# Repos #
#########

#- apt_repository: repo='deb http://ftp.au.debian.org/debian/ jessie main non-free contrib' state=present
#- apt_repository: repo='deb http://security.debian.org/ jessie/updates main non-free contrib' state=present
#- apt_repository: repo='deb http://ftp.au.debian.org/debian/ jessie-updates main non-free contrib' state=present
#- apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present

#- name: Remove Debian Australia Repo (main, contrib, non-free)
#  apt_repository: repo='deb http://ftp.au.debian.org/debian/ bullseye main contrib non-free' state=absent

#- name: Remove Debian Source Repo (main)
#  apt_repository: repo='deb-src http://ftp.debian.org/debian/ stretch main' state=absent

#- name: Add Debian Repo (main, contrib, non-free)
#  apt_repository: repo='deb http://ftp.debian.org/debian/ bullseye main contrib non-free' state=present

#- name: Add Debian Source Repo (main)
#  apt_repository: repo='deb-src http://ftp.debian.org/debian/ stretch main' state=present

#- name: Add Debian Security Repo (main, contrib, non-free)
#  apt_repository: repo='deb http://security.debian.org/debian-security bullseye/updates main contrib non-free' state=present

#- name: Add Debian Source Security Repo (main)
#  apt_repository: repo=' deb-src http://security.debian.org/debian-security stretch/updates main' state=present

#- name: Add Debian Volatile Repo (main)
#  apt_repository: repo='deb http://ftp.debian.org/debian/ stretch-updates main' state=present

#- name: Add Debian Source Volatile Repo (main)
#  apt_repository: repo='deb-src http://ftp.debian.org/debian/ stretch-updates main' state=present

#- name: Adding Microsoft Repo
#  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main' state=present

##########
# Update #
##########

- name: install aptitude
  apt: name=aptitude state=present

#- name : update cache if >4hr old
  #apt: cache_valid_time=14400 update_cache=yes upgrade=yes
  #apt: cache_valid_time=14400 update_cache=yes

#############################
# Standard Packages Present #
#############################

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_list:
     - acct
     - acpi
     - alpine
     - atop
     - auditd
     - autoconf
     - binutils
     - blktrace
     - cgroup-tools
     - cgroupfs-mount
     - cups-bsd
     - curl
     - dkms
     - dnsutils
     - dos2unix
     - dump
     - ethtool
     - finger
     - firmware-linux-free
     - firmware-linux-nonfree
     - firmware-realtek
     - git
     - gnupg
     - htop
     - iotop
     - ipcalc
     - jq
     - links2
     - ltrace
     - lynx
     - net-tools
     - nfswatch
     - nicstat
     - nmap
     - ntpdate
     - mailutils
     - mtr
     - octave
     - octave-general
     - octave-linear-algebra
     - octave-miscellaneous
     - octave-specfun
     - openntpd
     - openbsd-inetd
     - parallel
     - pcregrep
     - policycoreutils-python-utils
     - portsentry
     - postfix
     - procmail
     - quota
     - rsync
     - screen
     - sdate
     - selinux-basics
     - selinux-policy-default
     - semanage-utils
     - setools
     - slay
     - snapd
     - ssh
     - ssh-askpass
     - strace
     - stress
     - stress-ng
     - sudo
     - sysstat
     - tiptop
     - tshark
     - uptimed
     - vnstat
     - watchdog
     - whois
     - xfsdump
     - xfsprogs
     - youtube-dl

#########
# Files #
#########

#- copy: src=etc/inetd.conf dest=/etc/inetd.conf owner=root group=root mode=640
#- copy: src=etc/rsyncd.conf dest=/etc/rsyncd.conf owner=root group=root mode=640
#- copy: src=etc/rsyncd.exclude dest=/etc/rsyncd.exclude owner=root group=root mode=640
#- copy: src=etc/rsyncd.secrets dest=/etc/rsyncd.secrets owner=root group=root mode=600

###################
# Authorized_keys #
###################

#- name: Allow root@rigel to ssh to root
#  authorized_key:
#    user: root
#    state: present
#    key: "{{ lookup('file', 'rigel_dumpling_id_rsa.pub') }}"

###########
# SELinux #
###########

- name: Copy /usr/local/sbin/seLearn
  copy:
    src: seLearn
    dest: /usr/local/sbin/seLearn
    owner: root
    group: root
    mode: 0744

- name: Copy /usr/local/sbin/check_selinux_enforcing
  copy:
    src: check_selinux_enforcing
    dest: /usr/local/sbin/check_selinux_enforcing
    owner: root
    group: root
    mode: 0755

###########
# Sysstat #
###########

- name: Copy /etc/default/sysstat
  copy:
    src: sysstat
    dest: /etc/default/sysstat
    owner: root
    group: root
    mode: 0644
  register: sysstat

#- name: Restart service sysstat
#  systemd:
#    name: sysstat
#    state: restarted
#  when: sysstat.changed

############
# Watchdog #
############

- name: Copy watchdog default file
  copy:
    src: watchdog
    dest: /etc/default/watchdog
    owner: root
    group: root
    mode: 0644

- name: Copy watchdog.conf
  copy:
    src: watchdog.conf
    dest: /etc/watchdog.conf
    owner: root
    group: root
    mode: 0644
  register: watchdog

- name: Restart service watchdog
  systemd:
    name: watchdog
    state: restarted
  when: watchdog.changed

#- name: Start service watchdog
#  systemd:
#    name: watchdog
#    state: started
