#!/bin/bash

set -u

#
# Robert Brockway
#
# 12 June 2022
#

#
# Config
#

AUDITLOGS=/var/log/audit/audit.log*
MAKEFILE=/usr/share/selinux/devel/Makefile
PPFILE=local.pp
TEFILE=local.te

#
# Functions
#

buildPP()
{
	make -f $MAKEFILE $PPFILE &> /dev/null
	case $? in
	0)
		echo "PP file $PPFILE built successfully"
		;;
	*)
		error 60
		;;
	esac
}

buildTE()
{
	cat $AUDITLOGS | audit2allow -m local > $TEFILE 2> /dev/null
	case $? in
	0)
		echo "TE file $TEFILE built successfully"
		;;
	*)
		error 40
		;;
	esac

}

error()
{
	case $1 in
	10)
		MESSAGE="Unable to find command mktemp"
		;;
	12)
		MESSAGE="Unable to find command audit2allow"
		;;
	14)
		MESSAGE="Unable to find command semodule"
		;;
	20)
		MESSAGE="Unable to create temp dir $TMPDIR"
		;;
	25)
		MESSAGE="Unable to set current working directory to $TMPDIR"
		;;
	30)
		MESSAGE="Unable to execute semodule -DB"
		;;
	40)
		MESSAGE="Unable to build TE file $TEFILE"
		;;
	60)
		MESSAGE="Unable to build PP file $PPFILE"
		;;
	80)
		MESSAGE="Unable to load PP file $PPFILE"
		;;
	*)
		MESSAGE="Unknown error"
		;;
	esac

	echo $MESSAGE
	exit $1
}

initialise()
{
	command -v mktemp &> /dev/null
	case $? in
	0)
		true
		;;
	*)
		error 10
		;;
	esac

	command -v audit2allow &> /dev/null
	case $? in
	0)
		true
		;;
	*)
		error 12
		;;
	esac

	command -v semodule &> /dev/null
	case $? in
	0)
		true
		;;
	*)
		error 14
		;;
	esac

	TMPDIR=$(mktemp -d)
	case $? in
	0)
		true
		#echo "Temp directory $TMPDIR created successfully"
		;;
	*)
		error 20
		;;
	esac

	cd $TMPDIR
	case $? in
	0)
		true
		#echo "Current working directory set to $TMPDIR"
		;;
	*)
		error 25
		;;
	esac
}

loadPP()
{
	semodule -i $PPFILE &> /dev/null
	case $? in
	0)
		echo "PP File $PPFILE loaded successfully"
		;;
	*)
		error 80
		;;
	esac

}

unhideDenials()
{
	# If we hide denials we miss important details
	# This is mostly useful for the next run
	semodule -DB &> /dev/null
	case $? in
	0)
		echo "Denials unhidden"
		;;
	*)

		;;
	esac
}


#
# Main
#

initialise
unhideDenials
buildTE
buildPP
loadPP
